# Generated by Django 2.1.dev20170922190937 on 2018-05-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('guardian', models.CharField(max_length=200)),
                ('guardianType', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('sno', models.CharField(max_length=200)),
                ('voterId', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
